services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile-graphql
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
      - graphql-node-modules:/usr/app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: ${ENV:-development}
      PORT: 8080
      DATABASE_TYPE: postgres
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/examme
      DATABASE_SCHEMA: public
      CLIENT_URL: http://localhost:${FE_PORT}
    ports:
      - '${BE_PORT}:8080'

  ssr:
    build:
      context: .
      dockerfile: Dockerfile-ssr
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
      - ssr-node-modules:/usr/app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: ${ENV:-development}
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/examme
      GRAPHQL_URL: http://graphql:8080/graphql
    ports:
      - '${FE_PORT}:3000'

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: examme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'

volumes:
  graphql-node-modules:
  ssr-node-modules:
  postgres-data:
