services:
  be:
    build:
      context: ./api
      dockerfile: ../Dockerfile-be
    volumes:
      - ./api:/usr/app
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_TYPE: mongodb
      DATABASE_URL: mongodb://root:1111@mongo:27017/app?authSource=admin
      CLIENT_URL: http://localhost:${FE_PORT}
    ports:
      - "${BE_PORT}:8080"

  fe:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile-fe
    volumes:
      - ./frontend:/usr/app
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 8081
      VITE_API_BASE_URL: http://localhost:${BE_PORT}
    ports:
      - "${FE_PORT}:8081"

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1111
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"

volumes:
  mongo-data:
