import Link from 'next/link'
import SsrListControls from '../components/SsrListControls'
import { getExam, getExamList, getExamOptions, getHomeData, getQuestion, getQuestionList, getQuestions, getTag, getUser, getUserExams, getUserExamSessions, getUserList, getUsers } from '../lib/ssrData'

type Exam = { id: string; name: string; questionCount?: number; approvedQuestionCount?: number; requiredScore?: number }
type Question = { id: string; examId?: string; title: string; difficulty?: string }
export function ErrorPage() { return <><h1>Not found</h1><p>We couldn’t find that page.</p></> }
export function ExamList({ exams }: { exams: Exam[] }) { return <div className="grid gap-3 sm:grid-cols-2">{exams.map(e => <article className="rounded-lg border-0 bg-white p-4 shadow" key={e.id}><Link className="text-lg font-semibold" href={`/exams/${e.id}`}>{e.name}</Link><p>{e.approvedQuestionCount ?? 0}/{e.questionCount ?? 0} questions · required score {e.requiredScore ?? 0}%</p></article>)}</div> }
export function QuestionList({ questions }: { questions: Question[] }) { return <div className="space-y-2">{questions.map(q => <article className="rounded-lg border-0 bg-white p-4 shadow" key={q.id}><Link className="font-semibold" href={`/exams/${q.examId}/questions/${q.id}`}>{q.title}</Link><p>{q.difficulty ?? 'Difficulty not set'}</p></article>)}</div> }

export async function renderHome() {
  const d = await getHomeData(8)
  const exams = d.exams, questions = d.questions, tags = d.tags
  return <><h1 className="mt-1 font-primary text-3xl text-black">Home</h1><p className="mb-6 text-blue-gray-600">Explore exams, questions, and the ExamMe community.</p><div className="grid grid-cols-1 gap-8 xl:grid-cols-3"><main className="space-y-8 xl:col-span-2"><section><h2 className="mt-4 text-xl text-black">Popular topics</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">{tags.slice(0, 8).map(t => <Link href={`/tags/${t.slug}`} key={t.id}><div className="rounded-lg bg-gradient-to-br from-blue-gray-500 to-blue-gray-800 p-4 font-semibold text-white shadow">{t.name}</div></Link>)}</div></section><section><h2 className="mt-4 text-xl text-black">Popular exams</h2><div className="mt-3"><ExamList exams={exams.slice(0, 6)}/></div></section><section><h2 className="mt-4 text-xl text-black">Popular questions</h2><div className="mt-3"><QuestionList questions={questions.slice(0, 6)}/></div></section></main><aside className="space-y-8"><section><h2 className="mt-4 text-xl text-black">Latest exams</h2><div className="mt-3"><ExamList exams={exams.slice(0, 5)}/></div></section><section><h2 className="mt-4 text-xl text-black">Latest questions</h2><div className="mt-3"><QuestionList questions={questions.slice(0, 5)}/></div></section><section><h2 className="mt-4 text-xl text-black">Latest tags</h2><div className="mt-3 flex flex-wrap gap-3">{tags.slice(0, 5).map(t => <Link className="rounded-lg bg-white px-3 py-2 text-sm shadow" href={`/tags/${t.slug}`} key={t.id}>{t.name}</Link>)}</div></section></aside></div></>
}
export async function renderExams(params: Record<string, string | undefined> = {}) { const d = await getExamList(params); return <><h1 className="mt-1 font-primary text-black mb-6 text-3xl font-bold">Exams</h1><SsrListControls filters={params as Record<string, string>} page={d.page} size={d.size} hasNext={d.hasNext} options={{ approved: [{ value: 'yes', label: 'Approved' }, { value: 'no', label: 'Unapproved' }] }}/><ExamList exams={d.data}/></> }
export async function renderQuestions(params: Record<string, string | undefined> = {}) { const [d, exams] = await Promise.all([getQuestionList(params), getExamOptions()]); return <><h1 className="mt-1 font-primary text-black mb-6 text-3xl font-bold">Questions</h1><SsrListControls filters={params as Record<string, string>} page={d.page} size={d.size} hasNext={d.hasNext} options={{ approved: [{ value: 'yes', label: 'Approved' }, { value: 'no', label: 'Unapproved' }], exam: exams.map(exam => ({ value: exam.id, label: exam.name })), difficulty: [{ value: 'easy', label: 'Easy' }, { value: 'moderate', label: 'Moderate' }, { value: 'difficult', label: 'Difficult' }, { value: 'expert', label: 'Expert' }], type: [{ value: 'choice', label: 'Choice' }] }}/><QuestionList questions={d.data}/></> }
export async function renderExam(examId: string) { const d = { exam: await getExam(examId) }; if (!d.exam) return <ErrorPage/>; return <><h1 className="mt-1 font-primary text-black text-3xl font-bold">{d.exam.name}</h1><p className="mt-2">{d.exam.approvedQuestionCount ?? 0}/{d.exam.questionCount ?? 0} approved questions · required score {d.exam.requiredScore ?? 0}%</p><div className="mt-4 flex gap-2">{(d.exam.tags ?? []).map(t => <Link href={`/tags/${t.slug}`} key={t.id}>{t.name}</Link>)}</div></> }
export async function renderQuestion(questionId: string) { const d = { question: await getQuestion(questionId) }; if (!d.question) return <ErrorPage/>; return <><p><Link href={`/exams/${d.question.examId}`}>{d.question.exam?.name ?? 'Exam'}</Link></p><h1 className="mt-1 font-primary text-black mt-3 text-3xl font-bold">{d.question.title}</h1><p className="mt-2">{d.question.difficulty ?? 'Difficulty not set'}</p></> }
export async function renderUsers(params: Record<string, string | undefined> = {}) { const d = await getUserList(params); return <><h1 className="mt-1 font-primary text-black mb-6 text-3xl font-bold">Users</h1><SsrListControls filters={params as Record<string, string>} page={d.page} size={d.size} hasNext={d.hasNext}/><div className="grid gap-3 sm:grid-cols-2">{d.data.map(u => <article className="rounded-lg border-0 bg-white p-4 shadow" key={u.id}><Link className="font-semibold" href={`/users/${u.id}`}>{u.name || 'Unnamed user'}</Link><p>Joined {u.createdAt ? new Date(u.createdAt).toDateString() : 'recently'}</p></article>)}</div></> }
export async function renderUser(userId: string) {
  const [user, exams, sessions] = await Promise.all([getUser(userId), getUserExams(userId), getUserExamSessions(userId)])
  if (!user) return <ErrorPage/>
  return <><h1 className="mt-1 font-primary text-black text-3xl font-bold">{user.name || 'User profile'}</h1><p className="mt-2">Joined {user.createdAt ? new Date(user.createdAt).toDateString() : 'recently'}{user.updatedAt ? ` · Updated ${new Date(user.updatedAt).toDateString()}` : ''}</p><section className="mt-8"><h2 className="mb-4 text-2xl font-semibold">Exams</h2><ExamList exams={exams.data}/></section><section className="mt-8"><h2 className="mb-4 text-2xl font-semibold">Exam sessions</h2><div className="overflow-x-auto rounded-lg bg-white shadow"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Exam</th><th className="p-3">Progress</th><th className="p-3">Score</th><th className="p-3">Status</th><th className="p-3">Started</th></tr></thead><tbody>{sessions.map(session => <tr key={session.id} className="border-t"><td className="p-3">{session.exam ? <Link href={`/exams/${session.exam.id}`}>{session.exam.name}</Link> : session.examId}</td><td className="p-3">{session.answeredQuestionCount}/{session.questionCount}</td><td className="p-3">{session.correctAnswerCount ?? '—'}</td><td className="p-3">{session.completedAt ? 'Completed' : 'In progress'}</td><td className="p-3">{session.createdAt ? new Date(session.createdAt).toDateString() : 'N/A'}</td></tr>)}</tbody></table>{sessions.length === 0 && <p className="p-4">No exam sessions.</p>}</div></section></>
} 
export async function renderTag(tagSlug: string) { const tag = await getTag(tagSlug); return tag ? <><h1 className="mt-1 font-primary text-black text-3xl font-bold">{tag.name}</h1><p className="mt-2"><Link href={`/exams?tag=${tag.slug}`}>View exams tagged {tag.name}</Link></p></> : <ErrorPage/> }
