"""Canonical API route names and path templates."""

API_URL_ROUTES = {
    "api-certifications": "/certifications",
    "create-certification": "/certifications",
    "upload-public-file": "/public-file",
    "create-exam": "/exams",
    "create-question": "/exams/{exam_id}/questions",
    "api-questions": "/exams/{exam_id}/questions",
    "api-question": "/exams/{exam_id}/questions/{question_id}",
    "update-question": "/exams/{exam_id}/questions/{question_id}",
    "delete-question": "/exams/{exam_id}/questions/{question_id}",
    "create-exam-session": "/exams/{exam_id}/sessions",
    "api-exam-sessions": "/exam-sessions",
    "api-exam-session": "/exam-sessions/{session_id}",
    "answer-exam-session": "/exam-sessions/{session_id}/answers",
    "complete-exam-session": "/exam-sessions/{session_id}/complete",
    "api-exams": "/exams",
    "exam-hrefs": "/exams/hrefs",
    "exams-fragment": "/exams-fragment",
    "exam-comments-fragment": "/exams/{exam_id}/comments-fragment",
    "update-exam": "/exams/{exam_id}",
    "update-exam-status": "/exams/{exam_id}/status",
    "update-exam-impression": "/exams/{exam_id}/impression",
    "create-exam-comment": "/exams/{exam_id}/comment",
    "update-exam-comment": "/exams/{exam_id}/comments/{comment_id}",
    "create-contact-message": "/contacts/message",
    "tag-subscriptions": "/tag-subscriptions",
    "create-tag-subscription": "/tag-subscriptions",
    "delete-tag-subscription": "/tag-subscriptions/{tag_subscription_id}",
    "update-tag": "/tags/{slug}",
    "update-category": "/categories/{slug}",
    "api-tags": "/tags",
    "api-categories": "/categories",
    "tags-fragment": "/tags-fragment",
    "users-fragment": "/users-fragment",
    "update-user-status": "/users/{user_id}/status",
    "update-user-impression": "/users/{user_id}/impression",
    "update-user-activity-settings": "/users/{user_id}/activity-settings",
    "update-user-interests-settings": "/users/{user_id}/interests-settings",
    "update-user": "/users/{user_id}",
    "user-exams-fragment": "/users/{user_id}/exams-fragment",
    "generate-sitemap": "/generate-sitemap",
    "drop-cdn-cache": "/drop-cdn-cache",
}
