"""Canonical web route names and path templates."""

WEB_AUTH_URL_ROUTES = {
    "login": "/login",
    "login-callback": "/login-callback",
    "logout": "/logout",
    "logout-callback": "/logout-callback",
}

WEB_URL_ROUTES = WEB_AUTH_URL_ROUTES | {
    "index": "/",
    "static-file": "/{filename:path}",
    "new-exam": "/exams/new",
    "exams": "/exams",
    "new-question": "/exams/{exam_id}/questions/new",
    "edit-question": "/questions/{question_id}/edit",
    "question-by-id": "/questions/{question_id}",
    "question-by-slugs": "/@{user_slug}/{exam_slug}/{question_slug}",
    "questions-all": "/questions",
    "exam-sessions": "/exam-sessions",
    "exam-session": "/exam-sessions/{session_id}",
    "tags": "/tags",
    "categories": "/categories",
    "certifications": "/certifications",
    "new-certification": "/certifications/new",
    "certification": "/certifications/{slug}",
    "exam": "/exams/{exam_id}",
    "edit-exam": "/exams/{exam_id}/edit",
    "exams-by-slugs": "/{slugs_path:path}/exams",
    "contacts": "/contacts",
    "edit-tag": "/tags/{slug}/edit",
    "edit-category": "/categories/{slug}/edit",
    "users": "/users",
    "users-by-slugs": "/{type}/users",
    "user": "/users/{user_id}",
    "edit-user": "/users/{user_id}/edit",
    "login": "/login",
    "login-callback": "/login-callback",
    "logout": "/logout",
    "logout-callback": "/logout-callback",
    "policy": "/privacy-policy",
    "rules": "/rules",
    "terms": "/terms-of-service",
    "earn": "/earn-with-us",
    "utils": "/utils",
    "user-by-slug": "/@{slug}",
    "exam-by-slugs": "/@{user_slug}/{exam_slug}",
}
